name: Windows C/C++ Build & Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016]
    steps:
    - uses: actions/checkout@v2

    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout --force 2020.01
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install fmt:x64-windows

    - name: Configure sequence
      run: |
        mkdir build 
        cd build 
        cmake .. -DSEQUENCE_BUILD_TESTS=1 -DCMAKE_BUILD_TYPE=Release -DSEQUENCE_FMT_EXTERNAL=1 -DCMAKE_TOOLCHAIN_FILE=${{github.workspace }}/../vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build sequence lib
      run: cmake --build build --target sequence tests

    - name: Run tests
      run: cd build/bin && ./tests
