name: Windows C/C++ Build & Test

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

jobs:

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
#        os: [windows-latest, windows-2016]
    steps:
    - uses: actions/checkout@v2
      
    - name: "clone fmt"
      run: git clone https://github.com/fmtlib/fmt.git
    - name: configure
      run: cd fmt && mkdir build && cd build && cmake ..
    - name: build
      run: cd fmt && cmake --build build
    - name: install
      run: cd fmt && cmake --build build --target install

    - name: configure
      run: mkdir build && cd build && cmake .. -DSEQUENCE_BUILD_TESTS=1 -DCMAKE_BUILD_TYPE=Release -DSEQUENCE_FMT_EXTERNAL=1  -Dfmt_DIR="C:\\Program Files (x86)\\FMT\\lib\\cmake\\fmt\\fmt-config.cmake"
      
    - name: search include dir
      run: dir "C:\\Program Files (x86)\\FMT"

    - name: search include dir
      run: dir "C:\\Program Files (x86)\\FMT\\include"

    - name: build
      run: export CXXFLAGS=-I "C:\\Program Files (x86)\\FMT\\include" && cmake --build build --target sequence tests

    - name: "Run tests"
      run: cd build/bin && ./tests
