name: C/C++ Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "INFO: OS"
      run: uname -a
    - name: "INFO: gcc"
      run: gcc --version
    - name: "INFO: cmake"
      run: cmake --version

    - name: "Get fmt::fmt dependency"
      run: sudo apt-get install -y libfmt-dev

    - name: "Configure sequence"
      run: cmake -S . -B build -DSEQUENCE_BUILD_TESTS=1 -DCMAKE_BUILD_TYPE=Release -DSEQUENCE_FMT_EXTERNAL=1

    - name: "Build sequence"
      run: cmake --build build --target sequence tests

    - name: "Run tests"
      run: ./build/bin/tests

    - name: "Run tests"
      run: cd build/bin && ./tests

  # build-windows:

  #   runs-on: ${{ matrix.os }}
  #   strategy:
  #     matrix:
  #       os: [windows-latest, windows-2016]
    
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: configure
  #     run: mkdir build && cd build && cmake ..
  #   - name: build
  #     run: cmake --build build --config Debug
  #   - name: test
  #     run: cd build && ctest